server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
    #连接仓库

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mzwmzw744/springcloud-config.git